# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTodo = channel.unary_unary(
        '/gRPC_demo.TodoService/AddTodo',
        request_serializer=todo__pb2.AddTodoRequest.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTodo': grpc.unary_unary_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=todo__pb2.AddTodoRequest.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gRPC_demo.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
